### PR TITLE
Update for 2021

### PR DESCRIPTION
**Pull request by ghost**
Hi,

I updated the wpilib ruby cask to extract the artifacts from the new installer.
I've tested this on my personal MacBook Air and it seems to work well.

Noam from MisCar 1574

### CODE REVIEW

**Review by AustinShalit — APPROVED** [review]

**Comment by AustinShalit** [comment]
Hi Noam! Thank you for updating this. Please tell Dan B and everyone over there that I say hello. --Austin

**Comment by noamzaks** [comment]
Hi @AustinShalit, thank you for merging our update.
I just notice there is some issue regarding code signing the executables. When I build robot code my mac displays a message 'Apple cannot check it for malicious software' (then I have to go to System Preferences's Security & Privacy and manually 'Allow' opening all of these executables). If I remember correctly this also happened with last year's WPILib macOS Installation, but the 2021 installer fixed it.
Do you know about such a fix, and are we able to implement it in the homebrew script?

On another note, warmest and best regards from all of the Bleiberg family. Hope to see you next time you're in the area.

Thanks,
Noam

**Comment by AustinShalit** [comment]
That should be fixed outside of the installer but @prateekma might know a little more on the subject.

**Comment by prateekma** [comment]
We don't actually notarize any of the binaries yet; all we do is sign them so that we can hopefully include them in the notarization next year. 

The way the installer works is that when the tar extraction is done, it doesn't actually preserve the com.apple.quarantine flag. This flag is what triggers Gatekeeper.

We could add something to the brew script to strip that flag from the tar before extraction. I think there are other utilities on homebrew that do something similar.

**Pull request merged**
